#!/usr/bin/env ansible-playbook
---
- name: Default Service state. 
  hosts: drbd-cluster

  tasks:
  - name: disable unused services
    service:
      name: lvm2-clvmd
      enabled: false
      state: stopped
    with_items:
     - lvm2-clvmd
     - dlm
     - drdb
     - haveged
     - heartbeat
     - pacemaker
     - pcsd
     - corosync
     - ocfs2
     - o2cb
